name = "hammal"
account_id = "336d11932290c57e26c5c24df5b4604d"
main = "src/index.ts"
workers_dev = true
compatibility_date = "2024-06-08"

kv_namespaces = [
	 { binding = "HAMMAL_CACHE", id = "28142a5747cb4cb699bb4c0f9e53c2e8" }
]
